development:
  -
    id: "3089417f22"
    name: "ODI Newsletter"
    help: "News from the ODI"
production:
  -
    id: "380ec5286f"
    name: "ODI Newsletter"
    help: "News from the ODI"
test:
  -
    id: "3089417f22"
    name: "ODI Newsletter"
    help: "News from the ODI"
